-- =====================================================================
-- UPDATE BANK SOAL → 100 soal pilihan ganda (ISO 9001:2026)
-- Untuk instalasi yang SUDAH berjalan: jalankan file ini di Supabase → SQL Editor.
-- Hanya mengganti kunci jawaban di tabel grading_config. Tabel peserta/batch tidak disentuh.
-- Aman dijalankan ulang.
-- =====================================================================

insert into public.grading_config (id, config) values (1, $cfg${
 "version": "qb100-2026-v1",
 "mc": {
  "1": "C",
  "2": "B",
  "3": "C",
  "4": "D",
  "5": "B",
  "6": "B",
  "7": "B",
  "8": "C",
  "9": "B",
  "10": "C",
  "11": "A",
  "12": "C",
  "13": "B",
  "14": "C",
  "15": "B",
  "16": "C",
  "17": "A",
  "18": "B",
  "19": "C",
  "20": "B",
  "21": "B",
  "22": "D",
  "23": "B",
  "24": "B",
  "25": "B",
  "26": "B",
  "27": "C",
  "28": "B",
  "29": "B",
  "30": "A",
  "31": "D",
  "32": "D",
  "33": "D",
  "34": "D",
  "35": "D",
  "36": "D",
  "37": "B",
  "38": "B",
  "39": "C",
  "40": "A",
  "41": "A",
  "42": "D",
  "43": "B",
  "44": "B",
  "45": "C",
  "46": "B",
  "47": "D",
  "48": "D",
  "49": "D",
  "50": "B",
  "51": "D",
  "52": "C",
  "53": "D",
  "54": "A",
  "55": "D",
  "56": "B",
  "57": "A",
  "58": "A",
  "59": "D",
  "60": "B",
  "61": "D",
  "62": "B",
  "63": "B",
  "64": "A",
  "65": "A",
  "66": "A",
  "67": "C",
  "68": "B",
  "69": "D",
  "70": "B",
  "71": "B",
  "72": "A",
  "73": "A",
  "74": "B",
  "75": "D",
  "76": "D",
  "77": "A",
  "78": "A",
  "79": "A",
  "80": "B",
  "81": "D",
  "82": "A",
  "83": "D",
  "84": "D",
  "85": "A",
  "86": "D",
  "87": "B",
  "88": "D",
  "89": "A",
  "90": "B",
  "91": "A",
  "92": "D",
  "93": "D",
  "94": "D",
  "95": "C",
  "96": "D",
  "97": "A",
  "98": "B",
  "99": "A",
  "100": "C"
 },
 "comp": {
  "1": "FND",
  "2": "FND",
  "3": "FND",
  "4": "FND",
  "5": "FND",
  "6": "FND",
  "7": "FND",
  "8": "FND",
  "9": "FND",
  "10": "FND",
  "11": "FND",
  "12": "FND",
  "13": "FND",
  "14": "FND",
  "15": "FND",
  "16": "CTX",
  "17": "CTX",
  "18": "CTX",
  "19": "CTX",
  "20": "CTX",
  "21": "CTX",
  "22": "CTX",
  "23": "CTX",
  "24": "CTX",
  "25": "CTX",
  "26": "CTX",
  "27": "CTX",
  "28": "LDR",
  "29": "LDR",
  "30": "LDR",
  "31": "LDR",
  "32": "LDR",
  "33": "LDR",
  "34": "LDR",
  "35": "LDR",
  "36": "LDR",
  "37": "LDR",
  "38": "LDR",
  "39": "R&O",
  "40": "R&O",
  "41": "R&O",
  "42": "R&O",
  "43": "R&O",
  "44": "R&O",
  "45": "R&O",
  "46": "R&O",
  "47": "R&O",
  "48": "R&O",
  "49": "R&O",
  "50": "R&O",
  "51": "SUP",
  "52": "SUP",
  "53": "SUP",
  "54": "SUP",
  "55": "SUP",
  "56": "SUP",
  "57": "SUP",
  "58": "SUP",
  "59": "SUP",
  "60": "SUP",
  "61": "SUP",
  "62": "SUP",
  "63": "SUP",
  "64": "SUP",
  "65": "SUP",
  "66": "SUP",
  "67": "SUP",
  "68": "SUP",
  "69": "SUP",
  "70": "SUP",
  "71": "OPS",
  "72": "OPS",
  "73": "OPS",
  "74": "OPS",
  "75": "OPS",
  "76": "OPS",
  "77": "OPS",
  "78": "OPS",
  "79": "OPS",
  "80": "OPS",
  "81": "OPS",
  "82": "OPS",
  "83": "PER",
  "84": "PER",
  "85": "PER",
  "86": "PER",
  "87": "PER",
  "88": "PER",
  "89": "PER",
  "90": "PER",
  "91": "PER",
  "92": "PER/IMP",
  "93": "PER/IMP",
  "94": "PER/IMP",
  "95": "PER/IMP",
  "96": "PER/IMP",
  "97": "PER/IMP",
  "98": "PER/IMP",
  "99": "PER/IMP",
  "100": "PER/IMP"
 },
 "exp": {
  "1": "QMS berorientasi pada pemenuhan persyaratan produk/jasa, customer satisfaction, serta pengelolaan dan improvement.",
  "2": "Persyaratan utama sistem berada pada Klausul 4–10.",
  "3": "PDCA dapat diterapkan pada seluruh proses dan QMS secara keseluruhan.",
  "4": "Risk-based thinking bukan berarti menghilangkan seluruh risiko.",
  "5": "Process approach melihat proses sebagai aktivitas yang saling terkait dan berinteraksi untuk menghasilkan hasil yang dimaksudkan.",
  "6": "Input proses dapat berasal dari output proses sebelumnya atau sumber lain yang relevan.",
  "7": "Ketiganya saling memperkuat dalam pengelolaan QMS.",
  "8": "Shall digunakan untuk requirement.",
  "9": "Should menunjukkan recommendation.",
  "10": "May menunjukkan permission.",
  "11": "Can menunjukkan possibility atau capability.",
  "12": "Struktur klausul tidak dimaksudkan sebagai model dokumentasi organisasi.",
  "13": "Keduanya memiliki nuansa penggunaan yang berbeda.",
  "14": "Ini merupakan pembedaan istilah dalam draft.",
  "15": "Annex A bersifat informatif.",
  "16": "Klausul 4.1 mencakup isu internal dan eksternal yang relevan.",
  "17": "Relevansi ditentukan terhadap purpose dan strategic direction.",
  "18": "Draft secara eksplisit meminta penentuan relevansi climate change.",
  "19": "Yang penting adalah penentuan relevansi yang dapat dipertanggungjawabkan.",
  "20": "Ada hubungan potensial dengan supply chain, process performance dan customer.",
  "21": "Gangguan supply chain dapat menjadi jalur dampak.",
  "22": "Berbagai sumber informasi dapat digunakan.",
  "23": "Interested parties dapat mencakup berbagai pihak yang relevan.",
  "24": "Relevansi terhadap QMS perlu ditentukan.",
  "25": "Draft meminta monitoring dan review.",
  "26": "Persyaratan customer perlu dipahami dan dinilai terhadap QMS.",
  "27": "Pengecualian tidak boleh menyebabkan kegagalan mencapai conformity.",
  "28": "QMS perlu diintegrasikan ke proses bisnis.",
  "29": "Fokusnya pada intended results.",
  "30": "Keduanya mendapat penekanan eksplisit.",
  "31": "Culture tercermin dalam nilai, sikap dan praktik.",
  "32": "Ketiganya dapat saling terkait.",
  "33": "Semua merupakan bagian customer focus.",
  "34": "Kasus menghubungkan ketiganya.",
  "35": "Semua merupakan karakteristik quality policy.",
  "36": "Semua relevan.",
  "37": "Top management memiliki accountability atas effectiveness QMS.",
  "38": "Complaint merupakan sumber informasi performance dan improvement.",
  "39": "Keduanya perlu ditentukan.",
  "40": "Konteks dan interested party requirements menjadi input penting.",
  "41": "Risk dikaitkan dengan conformity dan intended results.",
  "42": "Ketiga aspek diperlukan.",
  "43": "Opportunity diarahkan pada desirable effects.",
  "44": "Opportunity perlu dianalisis dan dievaluasi.",
  "45": "Manfaat dan potensi undesirable effects perlu dilihat bersama.",
  "46": "Keduanya terintegrasi dalam planning.",
  "47": "Semua relevan.",
  "48": "Ketiganya diperlukan.",
  "49": "Semua relevan.",
  "50": "Perubahan perlu dikelola dengan mempertimbangkan dampaknya terhadap QMS.",
  "51": "Semua merupakan kebutuhan resources.",
  "52": "Keduanya dipertimbangkan.",
  "53": "Infrastructure mencakup berbagai fasilitas dan ICT.",
  "54": "ICT dapat merupakan bagian infrastructure.",
  "55": "Ketiga jenis faktor dapat relevan.",
  "56": "Faktor lingkungan operasi proses perlu dinilai relevansinya.",
  "57": "Yang penting validitas hasil pengukuran.",
  "58": "Interval dapat ditentukan berdasarkan intended use dan risk.",
  "59": "Ketiganya membentuk competence.",
  "60": "Gap perlu ditangani dengan tindakan yang sesuai.",
  "61": "Ketiganya termasuk awareness.",
  "62": "Communication dipandang sebagai proses yang perlu direncanakan.",
  "63": "Protection dan access control diperlukan.",
  "64": "Knowledge mendukung operasi dan pencapaian hasil.",
  "65": "Pengetahuan kritis dapat hilang.",
  "66": "Ini merupakan pendekatan lifecycle yang dibahas dalam materi.",
  "67": "Kebutuhan dan effectiveness lebih penting daripada jumlah.",
  "68": "Obsolete information perlu dikendalikan.",
  "69": "Semua dapat menjadi external documented information.",
  "70": "Effectiveness tidak ditentukan oleh jumlah dokumen.",
  "71": "Operasi perlu dilakukan dalam kondisi terkendali.",
  "72": "Risk-based thinking membantu membangun pengendalian operasi.",
  "73": "Capability perlu direview sebelum commitment.",
  "74": "Customer commitment perlu berdasarkan kemampuan aktual.",
  "75": "Ketiganya dapat menjadi pertimbangan sesuai konteks.",
  "76": "Ketiganya merupakan bentuk control yang relevan.",
  "77": "Verification mengecek kesesuaian terhadap input.",
  "78": "Validation berhubungan dengan intended use/application.",
  "79": "External provision tetap perlu dikendalikan sesuai kebutuhan.",
  "80": "External provider yang memengaruhi QMS perlu dikendalikan.",
  "81": "Metode penanganan dipilih sesuai kondisi.",
  "82": "Perubahan perlu direncanakan dan dikendalikan.",
  "83": "Ketiganya merupakan rangkaian performance evaluation.",
  "84": "Planning monitoring and measurement mencakup elemen tersebut.",
  "85": "Customer satisfaction merupakan bagian performance monitoring.",
  "86": "Berbagai sumber dapat digunakan.",
  "87": "Satu angka tidak cukup tanpa analysis and evaluation.",
  "88": "Semua merupakan input penting untuk audit program.",
  "89": "Risk proses menjadi pertimbangan.",
  "90": "Efektivitas audit bukan jumlah temuan semata.",
  "91": "Management review mendukung evaluasi dan keputusan manajemen.",
  "92": "Ketiganya merupakan input relevan.",
  "93": "Semua relevan.",
  "94": "Semua merupakan area keputusan.",
  "95": "Continual improvement merupakan requirement.",
  "96": "Improvement dapat dipicu oleh berbagai sumber.",
  "97": "Corrective action diarahkan pada penyebab dan recurrence.",
  "98": "Draft memberi ruang penentuan kebutuhan corrective action berdasarkan konteks.",
  "99": "Mengganti orang belum tentu mengatasi systemic cause.",
  "100": "Pendekatan sistem menghubungkan berbagai elemen QMS."
 }
}$cfg$::jsonb)
on conflict (id) do update set config = excluded.config;

-- OPSIONAL — hapus data peserta uji/versi lama (JANGAN dijalankan bila ada data peserta asli yang masih diperlukan):
-- delete from public.attempts;
